// ═══════════════════════════════════════════════════════════════
// netscape-cookies.ts — Netscape cookies.txt 纯格式化（无 Electron 依赖）
// SRC ytdlp-gate.js exportCookiesForPlatform 的序列化段 1:1：域补点前缀、
// 无过期时间默认 +30 天、不发 #HttpOnly_ 前缀（SRC 口径；httpOnly 属性不进
// Netscape 行，cookie 本身仍随行导出，yt-dlp 按普通 cookie 发送）。
// 单独成模块：host 侧 ytdlp 门（后续工作包）与壳层共用，且可脱离
// Electron 做单测。
// ═══════════════════════════════════════════════════════════════

export interface NetscapeCookieInput {
  domain: string
  path?: string
  secure: boolean
  expirationDate?: number
  name: string
  value: string
}

/** 单条 cookie → Netscape 行 */
export function formatNetscapeCookie(c: NetscapeCookieInput): string {
  const domain = c.domain.startsWith('.') ? c.domain : '.' + c.domain
  const exp = c.expirationDate
    ? Math.round(c.expirationDate)
    : Math.round(Date.now() / 1000 + 86400 * 30)
  return `${domain}\tTRUE\t${c.path || '/'}\t${c.secure ? 'TRUE' : 'FALSE'}\t${exp}\t${c.name}\t${c.value}`
}

/** cookie 集合 → Netscape 文件全文 */
export function formatNetscapeCookies(cookies: NetscapeCookieInput[]): string {
  let text = '# Netscape HTTP Cookie File\n# Generated by TinTin Client (embedded browser session)\n'
  for (const c of cookies) text += formatNetscapeCookie(c) + '\n'
  return text
}
